# Parameters used to generate this project with https://wcm.io/tooling/maven/archetypes/aem/

# basic properties
projectName=wcmio-graniteui-sample-app
groupId=io.wcm.samples
artifactId=io.wcm.wcm.ui.granite.sample-app
version=1.0.0-SNAPSHOT
package=io.wcm.wcm.ui.granite.sampleapp
packageGroupName=wcm-io-samples
aemAuthorPort=4502
aemPublishPort=4503

# feature flags
optionAemVersion=cloud
optionJavaVersion=11
optionAemServicePack=n
optionAemServicePackAPI=n
optionSlingModelsLatest=n
optionSlingInitialContentBundle=y
optionEditableTemplates=y
optionMultiBundleLayout=n
optionContextAwareConfig=n
optionFrontend=n
optionNodeJsPlugin=n
optionWcmioHandler=n
optionWcmioSiteApi=n
optionWcmioSiteApiGenericEdit=n
optionWcmioConga=y
optionAcsCommons=n
optionIntegrationTests=n
